apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-uat
  namespace: uat
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@negobot.co
    privateKeySecretRef:
      name: letsencrypt-uat
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx
