export const ProductParameterCsvFields = [
    'code',
    'name',
    'category',
    'subcategory',
    'price#min',
    'price#max',
    'price#weight',
    'price#step',
    'price#unit',
    'price#inverse',
    'quantity#min',
    'quantity#max',
    'quantity#weight',
    'quantity#step',
    'quantity#unit',
    'quantity#inverse',
];

export const ProcurementProductCsvFields = [
    'name',
    'category',
    'subcategory',
    'product_code',
    'description_1',
    'description_2',
    'uom',
    'price',
    'currency',
];
export const ProcurementProductCsvSampleValue = {
    name: 'test',
    category: 'test',
    subcategory: 'test_subcategory',
    product_code: 'test12345',
    description_1: 'test description',
    description_2: 'this is description 2',
    uom: 'kg',
    price: 123,
    currency: 'INR',
};

export const ProductParameterCsvSampleValue = {
    code: 'TEST1290',
    name: 'Test Product',
    category: 'Test Category',
    subcategory: 'Test SubCategory',
    'price#min': 20,
    'price#max': 30,
    'price#weight': 0.8,
    'price#step': 0.1,
    'price#unit': 'SGD',
    'price#inverse': 0,
    'quantity#min': 100,
    'quantity#max': 200,
    'quantity#weight': 0.2,
    'quantity#step': 5,
    'quantity#unit': 'KG',
    'quantity#inverse': 0,
};
