# Orb Dependencies
orbs:
  gcloud: circleci/gcp-cli@1.0.6
  gcr: circleci/gcp-gcr@0.0.2
  k8s: circleci/kubernetes@0.1.0
workflows:
  version: 2
  build_and_test:
    jobs:
      - negotiation_test
      - negotiations:
          filters:
            branches:
              only: master
          requires:
            - negotiation_test
      