export enum TemplateType {
    RFQInvitation = 'RFQInvitation',
    RFQOpened = 'RFQOpened',
    RFQDeadlineApproaching = 'RFQDeadlineApproaching',
    RFQAwarded = 'RFQAwarded',
    RFQAwardedWon = 'RFQAwardedWon',
    RFQAwardedLost = 'RFQAwardedLost',
    RFQAwardedPending = 'RFQAwardedPending',
    RFQAwardAccept = 'RFQAwardAccept',
    RFQAwardedReject = 'RFQAwardedReject',
    RFQSupplierOfferSubmitted = 'RFQSupplierOfferSubmitted',
    RFQRoundCompleted = 'RFQRoundCompleted',
    SupplierRoundOfferSubmittedProcurement = 'SupplierRoundOfferSubmittedProcurement',
    AllSuppliersRoundOfferSubmittedProcurement = 'AllSuppliersRoundOfferSubmittedProcurement',
    FinalRoundOfferSubmittedProcurement = 'FinalRoundOfferSubmittedProcurement',
    AutoAcceptanceScoreReached = 'AutoAcceptanceScoreReached',
    RFQCopilotOfferSubmitted = 'RFQCopilotOfferSubmitted',
    RFQCopilotDeadlineApproaching = 'RFQCopilotDeadlineApproaching',
    RFQExited = 'RFQExited',
}
